HELLO_WORLD_VERSION = 1.0
HELLO_WORLD_MODULE_MAKE_OPTS = KVERSION=$(LINUX_VERSION_PROBED)
HELLO_WORLD_SITE = $(HELLO_WORLD_PKGDIR)/src
HELLO_WORLD_SITE_METHOD = local

$(eval $(kernel-module))
$(eval $(generic-package))
